openapi: 3.0.3
info:
  title: Accounts service
  version: 0.1

paths:
  /api/v1/account/{accountId}:
    post:
      tags:
        - account
      summary: Perform financial operation on given account
      description: Perform financial operation on given account
      operationId: performAction

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AccountOperationDTO"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: string

    get:
      tags:
        - account
      summary: Get account information by user id
      description: Get account information by user id
      operationId: getAccountById

      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountDTO'
#        404:
#          description: Account not found
#          content:
#            application/json:
#              schema:
#                $ref: '#/components/schemas/AccountNotFoundError'
components:
  schemas:

    AccountOperationDTO:
      type: object
      properties:
        operationType:
          $ref: '#/components/schemas/AccountOperationType'
        amount:
          type: number
          format: double

    AccountOperationType:
      type: string
      nullable: false
      enum:
        - ADDITION
        - SUBTRACTION

    AccountDTO:
      type: object
      properties:
        balance:
          type: number
          format: double
